final: UtPodDriver.o UtPod.o Song.o
	g++ -std=c++0x -otest  UtPodDriver.o UtPod.o Song.o
driver: UtPodDriver.cpp UtPod.h Song.h
	g++ -std=c++0x -c UtPod_Driver.cpp
UtPod.o: UtPod.cpp UtPod.h Song.h
	g++ -std=c++0x -c UtPod.cpp
song.o: Song.cpp Song.h
	g++ -std=c++0x -c Song.cpp
